# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20171112_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='questions',
            new_name='question',
        ),
    ]
