# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20171113_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_count',
            field=models.IntegerField(default=0),
        ),
    ]
